# Set up Cygwin. Source: https://github.com/egor-tensin/setup-cygwin
name: compile_cygwin

on: [push]

permissions:
  contents: read


jobs:
  setup_cygwin:
    runs-on: windows-latest
    steps:
      - name: setup_cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          platform: x64
          packages: cmake git libwx_baseu3.0-devel libwx_gtk3u3.0-devel gcc-core gcc-g++ make gettext-devel
      - name: Checkout_git
        run: git clone --depth 1 https://github.com/wxMaxima-developers/wxmaxima.git
      - name: configure
        run: |
             mkdir build
             cd build
             cmake ../wxmaxima
             cd ..
      - name: compile
        run: |
             cd build
             find /cygdrive/d/a/wxmaxima
             C:/tools/cygwin/bin/make.exe
             cd ..
